### ISSUE TITLE
A bit confused on jabber-querybot setup...

### ISSUE THREAD

**Issue by marcogaio** [micressor/jabber-querybot#4]
Reading the docs and (with little knowledge) the perl code seems to me that jabber-querybot (eg, /usr/bin/jabber-querybot) on start load the file /etc/jabber-querybot/Querymodule.pm where they get:
1. the connection parameters
2. the definition of the run_query() function, that is called on every incoming messages.

I suppose i can run /usr/bin/jabber-querybot by unprivileged users; but there's some way to instruct them to get *configuration file* (/etc/jabber-querybot/Querymodule.pm) from, eg, the users home dir?

Also, there's some way to run different instances, eg on different XMPP accounts, using different config files?

Thanks.

**Comment by micressor** [comment]
Simplest way if you use debian version:

    cd /etc/jabber-querybot
    ln -s Querymodule.pm Your-own-module.pm

If you use source code version, you may change the jabber-querybot binarie.

Thanks for the hint. I'll update the readme how to do this.

**Comment by micressor** [comment]
Docs updated.

**Comment by marcogaio** [comment]
Ok, i've understood that. Good, docs now are better.

But i meant something different: if, in my box, user 'gaio' and user 'anna' need a bot for their XMPP account, how can i run two instance of jabebr-querybot against two different config file?

**Comment by micressor** [comment]
Ah! I will update the docs and let you know.

**Comment by micressor** [comment]
If your Querymodule.pm of the 2nd instance lies in /home/2nd/lib, try this

    cd /etc/jabber-querybot
    mv Querymodule.pm Querymodule.pm.old
    perl -I /home/2nd/lib /usr/bin/jabber-querybot

Let me know, if this works.

**Comment by marcogaio** [comment]
Seems to work as expected.

As root:
```
mv /etc/jabber-querybot/Querymodule.pm /etc/jabber-querybot/Querymodule.pm.off
```
As user gaio:
```
mkdir .jabber-querybot
cp /etc/jabber-querybot/Querymodule.pm.off .jabber-querybot/Querymodule.pm
gaio@eraldo:~$ perl -I ~/.jabber-querybot /usr/bin/jabber-querybot
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "it_IT"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
info ---> Init(): Startup Marco Gaiarin - Risponditore...
debug ---> system_load_check(): Load 15min: 0.22 return 0
info ---> connect_bot();
info ---> connect_server(): Connecting to lilliput.linux.it jabber-server
info ---> Connect_server(): Connection successfully
info ---> connect_server(): Setting up callbacks
info ---> connect_server(): Send authentication gaio@lilliput.linux.it
info ---> connect_server(): Authentication 
Authentication status:  at /usr/bin/jabber-querybot line 628.
```

Still auth fail, but this is another bug,  eg #3 . Thanks! ;-)

**Comment by micressor** [comment]
README.md updated according to commit 1338677
